stages:
- generate
- check

generate-flake-ci:
  stage: generate
  script: ./.update-ci.sh > flake-ci.yml
  artifacts:
    paths:
      - flake-ci.yml

flake-ci:
  stage: check
  trigger:
    include:
      - artifact: flake-ci.yml
        job: generate-flake-ci
